[package]
name = "procon-test-rs"
version = "0.1.0"
authors = ["statiolake <statiolake@gmail.com>"]
edition = "2018"

[dependencies]
cli_test_dir = "0.1.7"
terminal_size = "0.1.8"
splitv = "0.1.1"
itertools = "0.8.0"
